//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn2012.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public double MoveSpeed { get; set; }
        public int HP { get; set; }
        public string Lore { get; set; }
        public int AttackTypeId { get; set; }
    
        public virtual AttackType AttackType { get; set; }
    }
}
