//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn2012.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hero
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int HP { get; set; }
        public int AttackTypeId { get; set; }
        public string Lore { get; set; }
        public double MoveSpeed { get; set; }
    
        public virtual AttackType AttackType { get; set; }
    }
}
