//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Learn2012.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserKatka
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int KatkaId { get; set; }
        public int TeamIndex { get; set; }
    
        public virtual Katka Katka { get; set; }
        public virtual User User { get; set; }
    }
}
